---

- name: Check if remote_syslog2 is installed
  command: dpkg-query -W remote_syslog2
  register: remote_syslog2_check_deb
  failed_when: remote_syslog2_check_deb.rc > 1
  changed_when: remote_syslog2_check_deb.rc == 1
  tags: remote_syslog2

- name: Download remote_syslog2
  get_url:
    url="{{ remote_syslog2_download_path }}"
    dest="/tmp/remote_syslog2.deb"
    checksum="{{ remote_syslog2_download_checksum }}"
  when: remote_syslog2_check_deb.rc == 1
  tags: remote_syslog2

- name: Install remote_syslog2
  apt: deb="/tmp/remote_syslog2.deb"
  when: remote_syslog2_check_deb.rc == 1
  tags: remote_syslog2

- name: Install remote_syslog2 config
  template: src=log_files.yaml dest=/etc/log_files.yml mode=0644 owner=root
  tags: remote_syslog2

- name: Enable remote_syslog2
  service: name=remote_syslog state=started enabled=true
  tags: remote_syslog2
