---
- name: 'Update APT package cache'
  apt: update_cache=yes

- name: 'Upgrade APT to the lastest packages'
  apt: upgrade=safe

- name: install dnsmasq
  apt: pkg=dnsmasq state=present
  tags: networking

- name: set up dnsmasq
  template: src=dnsmasq.conf dest=/etc/dnsmasq.conf
  tags: networking

- name: enable dnsmasq on boot
  service: name=dnsmasq enabled=yes
  tags: networking

- name: set up dhcpcd
  template: src=dhcpcd.conf dest=/etc/dhcpcd.conf owner=root group=netdev mode=u=rw,g=rw,o=r
  tags: networking

- name: set up network interfaces
  copy: src=interfaces dest=/etc/network/interfaces
  tags: networking
